### ISSUE TITLE
Spin out deploy rake tasks into new gem

### ISSUE THREAD

**Issue by jbrunton** [jbrunton/jbrunton.com#18]
A heroku deploy gem could be useful across projects.  Suggested behavior:
- Allow optional development, staging and production heroku servers.
- deploy:development, deploy:staging and deploy:production would deploy to appropriate servers with varying behavior:
  - deploy:development would push HEAD directly
  - deploy:staging would push the tip of master to staging, provided it's not ahead of origin
  - deploy:production would push the tip of master to production, provided that it's not ahead of origin; and, if there is a staging server, providing it's not ahead of staging.

Config file could look something like this:

```
apps:
  development: jbrunton-com-development
  staging: jbrunton-com-staging
  production: jbrunton-com

checks:
  staging:
    behind: true
  production:
    behind: true
    staged: true
```

Could probably build on top of https://github.com/fastestforward/heroku_san
